config/routes.rb
Rails.application.routes.draw do

  get 'registrations_disabled', to: 'pages#registrations_disabled', as: :edit_user_registration
  get 'registrations_disabled', to: 'pages#registrations_disabled', as: :new_user_registration

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'


  root to: 'homes#home' # redirects to other pages depending on user type/login status

  # TODO -- STRIPE ROUTE -- needs to be re-config'ed with Customers routes
  resources :charges, only: [:new]

  post '/charge', to: "charges#create_charge", as: 'charge'
  post '/add-payment', to: 'charges#create_source', as: 'add_payment'

  devise_for :users, controllers: { registrations: 'user/registrations' }  # includes [edit, new, create, update, destroy] for all types of profile

  get 'interpreters', to: 'user_views#index'
  get 'customers', to: 'user_views#index'
  get 'users/:id', to: 'user_views#show'

  get 'start', to: 'calls#start'
  get 'join', to: 'calls#join'

  get 'about', to: 'pages#aboutus'

  get 'dashboard', to: 'user_views#dashboard', as: 'dashboard'
  patch 'dashboard', to: 'user_views#update', as: 'dash_update'

  resources :calls, only: [:create]

  patch 'calls/:call_id/attachtwiliosid', to: 'calls#attach_twilio_sid'

  get 'api/v1/twiliojwt', to: 'calls#get_twilio_jwt'

  # TODO: fix with proper namespacing
  # namespace :api do
  #   namespace :v1 do
  #     get 'twiliojwt', to: 'calls#get_twilio_jwt'
  #   end
  # end

  get 'endcall', to: 'calls#end_call'

  get "icons/star_:pct", to: "icons#star", format: :svg

  get 'home', to: 'pages#home'

  #Reviews TODO
  resources :users do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [ :show, :edit ]


end

app/views/shared/_avatar.html.erb
<%

user ||= nil
img ||= nil
custom_styles ||= ''

class_list = 'gu-avatar '
class_list += (local_assigns[:classes] || '') # ???

scale_mappings = {
  xs: 1.0/3,
  small: 0.5,
  medium: 1,
  large: 1.8
}

scale = scale_mappings[scale] || scale || 1

style = <<~CSS
  width: #{(scale * 120).to_i}px;
  height: #{(scale * 120).to_i}px;
CSS

if user

  filename = user.avatar.filename
  photo = (filename && "#{ENV['CLOUDINARY_PUBLIC_PATH']}/g_face/#{filename}") || user.external_avatar

elsif img

  photo = img

else
  raise 'must supply either `user` or `img`'
end


if photo.nil?
  name = user.name
  initials = Utils.name_to_initials(name)
  colors = Utils.str_to_bg_and_fg_color(name)
  bg = colors[:bg]
  fg = colors[:fg]
  text_content = initials
  style += <<~CSS
    background: #{bg};
    color: #{fg};
    font-size: #{(scale * 4).to_i}em;
  CSS
else
  text_content = ''
  style += <<~CSS
    background: url(#{photo});
    background-size: cover;
  CSS
end

style += custom_styles

%>
<div title="<%= name %>" class="<%= class_list %>" style="<%= style %>">
  <%= text_content %>
</div>

app/views/shared/_edit_profile.html.erb
<div class="content">
    <div class="container-fluid">
        <div class="row">
        <div class="col-md-10 ml-auto mr-auto">
            <div class="card">
            <div class="card-body">
                <%= simple_form_for user, url: dash_update_path, method: :patch do |form| %>
                <div class="row">
                    <div class="col-md-5">
                      <div class="form-group">
                          <%= form.input :name %>
                      </div>
                    </div>
                    <div class="col-md-2">
                      <div class="form-group">
                          <%= form.input :gender, collection: ["Male", "Female", "Other"] %>
                      </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <%= form.input :language, collection: ["Auslan", "ASL"]%>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <% if current_user.interpreter? %>
                          <%= form.input :certifications, collection: ["NAATI 2", "NAATI 3"] %>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                    <div class="form-group">
                        <%= form.input :bio, placeholder: "A few words on your work experience" %>
                    </div>
                    </div>
                </div>
                <%= form.submit "Update", class: "btn btn-primary btn-link btn-wd btn-lg" %>
                <div class="clearfix"></div>
                <% end %>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>

    <%# <button type="button" class="btn btn-circle btn-xl-orange"><i class="fas fa-plus"></i></button> %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="material-icons">check_circle_outline</span>
    <span class="alert-inner"><%= notice %></span>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="material-icons">error_outline</span>
    <span class="alert-inner"><%= alert %></span>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% unless content_for?(:suppress_footer?) %>
  <footer class="footer footer-default">
    <div class="container">
      <nav class="float-left">
        <ul>
          <li>
            <%= link_to "About Us", about_path , class: "nav-link" %>
            </a>
          </li>
        </ul>
      </nav>
      <div class="copyright float-right">
        &copy;
        <script>
          document.write(new Date().getFullYear())
        </script> - made with <i class="material-icons icon icon-warning">favorite</i> by
        Team Gestuno at LeWagon #194.
      </div>
    </div>
  </footer>
<% end %>

app/views/shared/_history.html.erb
<div class="container">
    <div class="row">
        <!-- <div class="col-md-8"> -->
<!--             <div class="card card-plain">
                <div class="card-header card-header-primary">
                    <h4 class="card-title mt-0">Historical Table</h4>
                    <p class="card-category">Table table</p>
                </div> -->
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Duration</th>
                            <th>Cost</th>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Interpreter/Customer</td>
                                <td>12 mins</td>
                                <td>$12</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    <!-- </div> -->
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-transparent navbar-color-on-scroll fixed-top" color-on-scroll="100" id="sectionsNav">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "GESTUNO_LOGO_NOBCK.png", height: 30 %>
      <% end %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->

    <ul class="navbar-nav ml-auto" style="display: flex; flex-direction: row;">
      <% if user_signed_in? %>
        <!-- Links when logged in -->
      <li class="nav-item">
        <a href="#" class="btn btn-rose btn-raised btn-fab btn-round" data-toggle="dropdown" id='email'>
          <i class="material-icons">email</i>
        </a>
      </li>
      <li class="dropdown nav-item">
        <a href="#" class="profile-photo dropdown-toggle nav-link" data-toggle="dropdown">
          <div class="profile-photo-small">
            <%= render 'shared/avatar', user: current_user, scale: :xs %>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right" style="position: absolute;">
          <%= link_to "My profile", dashboard_path, class: "dropdown-item" %>

          <%= link_to "Edit account", edit_user_registration_path, class: "dropdown-item" %>

          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <!-- Login link (when logged out) -->
        <li><%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "btn btn-primary" %></li>
      <% end %>
    </ul>

  </div>
</nav>


  <% if !content_for?(:page_banner?) %>

    <div class='navbar navbar-color-on-scroll fixed-top navbar-transparent' style='position: relative; opacity: 0; z-index: -1000000'>
      <div style='height: 40px;'></div>
    </div>

  <% end %>

app/views/shared/_page_banner.html.erb
<%
  content_for(:page_banner?) { 'Je pense, donc je suis' }

  bg_img ||= 'https://res.cloudinary.com/dyocdwgu9/image/upload/v1543549512/gestuno/bkg4.jpg'
  height ||= '380px'
  parallax = true if parallax.nil?
  style ||= ''

  inline_styles = <<~CSS
    background-image: url(#{bg_img});
    height: #{height};
  CSS

  inline_styles << style
%>

<div class="page-header header-filter" data-parallax="<%= parallax %>" style="<%= inline_styles %>">
  <%= yield %>
</div>

app/views/shared/_profile.html.erb
<div class="main main-raised">
  <div class="profile-content">
    <div class="container">
      <div class="row">
        <div class="col-md-6 ml-auto mr-auto">
          <div class="profile">
            <div class="avatar gu-avatar-container">


              <%= render 'shared/avatar', user: user, scale: :large, classes: "img-raised img-fluid gu-raised-avatar" %>

              <!-- margin: -110px 0 20px 0; -->

              <% if user.interpreter? && user != current_user %>
                <% if user.online? %>
                  <%= form_tag(controller: :calls, action: :create, method: :post, recipient: user) do %>
                    <%= button_tag type: 'submit', class: 'call-button-start', title: 'Start call' do %>
                      <i class="fas fa-phone"></i>
                    <% end %>
                  <% end %>
                <% else %>
                  <div class='call-button-offline' title='Offline'>
                    <i class="material-icons">do_not_disturb</i>
                  </div>
                <% end %>
              <% end %>

            </div>

            <div class="name">
              <h3><%= user.name %></h3>
              <h5><%= user.role.capitalize %></h5>

              <% language_taglines = [user.language.capitalize]
                 language_taglines << user.certifications if user.interpreter?
              %>

              <h6><%= language_taglines.join(' | ') %></h6>
            </div>
          </div>
        </div>
      </div>
      <div class="description text-center">
        <p><%= user.bio %></p>
        <% if user.interpreter? %>
          <p><%= render 'shared/stars', rating: user.stars %></p>
          <br>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_stars.html.erb
<% if rating.nil?

  label = 'No ratings yet'

end %>

<div aria-label="<%= label %>" title="<%= label %>">
  <%
    if !rating

      %><span style='color: #aaa;'>N/A</span><%

    else
      5.times do |n|
        pct_ttl = rating * 20
        prev_pct = n * 20
        raw_val = pct_ttl - prev_pct
        if raw_val < 0
          pct = 0
        elsif raw_val > 20
          pct = 100
        else
          pct = (raw_val * 5).to_i
        end
        %><img src="/icons/star_<%= pct %>.svg" alt="" style="width: 20px"><%
      end
    end
  %>
</div>

app/views/shared/_table.html.erb
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div class="table-responsive">
    <table class="table table-shopping">
      <thead>
        <tr>
          <th class="text-center"></th>
          <th>Name</th>
          <th class="th-description">Language</th>
          <% if @user_type == :interpreter %>
            <th class="th-description">Rating</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr
            class="gu-clickable-table-row"
            data-link="<%= '/users/' + user.id.to_s %>"
            onclick="window.location = this.dataset.link"
          >
            <td>
              <div class="img-container">
                <%= render 'shared/avatar', user: user, scale: :small %>
              </div>
            </td>
            <td class="td-name">
              <p><strong><%= user.name %></strong></p>
            </td>
            <td>
              <%= user.language %>
            </td>
            <% if @user_type == :interpreter %>
              <td><%= render 'shared/stars', rating: user.stars, label: "Average rating: #{user.stars}" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_toggle.html.erb
<p>Toggle to ON to start interpreting!</p>
<br>
<label class="switch switch_type1" role="switch">
  <input type="checkbox" class="switch__toggle" checked>
  <span class="switch__label"></span>
</label>