config/routes.rb
Rails.application.routes.draw do

  get 'registrations_disabled', to: 'pages#registrations_disabled', as: :edit_user_registration
  get 'registrations_disabled', to: 'pages#registrations_disabled', as: :new_user_registration

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'


  root to: 'homes#home' # redirects to other pages depending on user type/login status

  # TODO -- STRIPE ROUTE -- needs to be re-config'ed with Customers routes
  resources :charges, only: [:new]

  post '/charge', to: "charges#create_charge", as: 'charge'
  post '/add-payment', to: 'charges#create_source', as: 'add_payment'

  devise_for :users, controllers: { registrations: 'user/registrations' }  # includes [edit, new, create, update, destroy] for all types of profile

  get 'interpreters', to: 'user_views#index'
  get 'customers', to: 'user_views#index'
  get 'users/:id', to: 'user_views#show'

  get 'start', to: 'calls#start'
  get 'join', to: 'calls#join'

  get 'about', to: 'pages#aboutus'

  get 'dashboard', to: 'user_views#dashboard', as: 'dashboard'
  patch 'dashboard', to: 'user_views#update', as: 'dash_update'

  resources :calls, only: [:create]

  patch 'calls/:call_id/attachtwiliosid', to: 'calls#attach_twilio_sid'

  get 'api/v1/twiliojwt', to: 'calls#get_twilio_jwt'

  # TODO: fix with proper namespacing
  # namespace :api do
  #   namespace :v1 do
  #     get 'twiliojwt', to: 'calls#get_twilio_jwt'
  #   end
  # end

  get 'endcall', to: 'calls#end_call'

  get "icons/star_:pct", to: "icons#star", format: :svg

  get 'home', to: 'pages#home'

  #Reviews TODO
  resources :users do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [ :show, :edit ]


end

app/controllers/charges_controller.rb
require "stripe"

class ChargesController < ApplicationController
  before_action :stripe_params, only: [:create_source, :retrieve, :create_charge]

  include ChargesHelper
  include Utils

  def new
  end

  def create_source
    # *********** RECEIVE the payment-form from charges/new **********
    # FIRST, see if customer exists? && CHECK if USER has STRIPE_ID
    # IF NOT: create
    # Stripe::Customer.create({source: params[:stripeSource], email: current_user.email})
    # ELSE RETRIEVE CUSTOMER OBJECT & UPDATE W/ NEW SOURCE
    if current_user.customer? && current_user.stripe_id == nil
      customer = Stripe::Customer.create(
        :source => params[:stripeSource],
        :email => current_user.email
      )
      current_user.update(stripe_id: customer.id)
    else
      customer = Stripe::Customer.retrieve(current_user.stripe_id)
      customer.source = params[:stripeSource]
      customer.save
    end
    redirect_to dashboard_path
  end

  def create_charge
    # AFTER CALL: POST to create_charge w/ duration & call id
    # CALCULATE COST
    # USE STRIPE_ID to retrieve STRIP CUSTOMER OBJECT
    # CREATE stripe CHARGE w/ customer: user.stripe_id
    # UPDATE the call object as paid/unpaid, amount charged.
    @call = Call.find(session[:call_id])
    @duration = @call.duration
    @aud_cents_cost = ChargesHelper.aud_cents_cost_of(@call)
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    charge = Stripe::Charge.create({
      amount: @aud_cents_cost,
      currency: 'aud',
      customer: current_user.stripe_id
    });

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
    if charge.status == "succeeded"
      "Payment was successful! You paid #{Utils.format_aud_cents(@aud_cents_cost)}."
    else
      "Oops! This was not paid yet. Still owing #{Utils.format_aud_cents(@aud_cents_cost)}."
    end
    # TODO SOPHIE TO FIX PATHS
    redirect_to dashboard_path
  end

  # def create
  # TODO SOPHIE - CARD ERROR

  # end

  # Amount in cents
  #   @amount = 150

  #   customer = Stripe::Customer.create(
  #     :email => params[:stripeEmail],
  #     :source  => params[:stripeToken]
  #   )

  #   charge = Stripe::Charge.create(
  #     :customer    => customer.id,
  #     :amount      => @amount,
  #     :description => 'Create your Stripe Payment Account here',
  #     :currency    => 'AUD'
  #   )

  #   debugger

  #   # Create a Customer:

  #   customer = Stripe::Customer.create({
  #                                        source: 'tok_mastercard',
  #                                        email: 'paying.user@example.com',
  #   })

  #   # Charge the Customer instead of the card:

  #   # YOUR CODE: Save the customer ID and other info in a database for later.

  #   # When it's time to charge the customer again, retrieve the customer ID.
  #   charge = Stripe::Charge.create({
  #                                    amount: 1500, # $15.00 this time
  #                                    currency: 'aud',
  #                                    customer: @user.stripe_id, # Previously stored, then retrieved
  #   })
  # end

  private

  def stripe_params
    Stripe.api_key = ENV['STRIPE_SECRET_KEY']
  end

end

app/helpers/charges_helper.rb
module ChargesHelper

  class << self

    def aud_cents_cost_of(call)
      raw = (call.duration * 1.5).to_i
      min = 100

      raw > min ? raw : min
    end

    def aud_cents_earnings_from(call)
      raw = (call.duration * 1.25).to_i
      min = 75

      raw > min ? raw : min
    end

  end
end

app/views/charges/_create.html.erb
<!-- STRIPE - PAYMENT SUCCESS MESSAGE -->
<h2>Thank you for calling with <%= @call.interpreter.name %></h2>
<p>You paid <strong><%= @cost %></strong> for <strong><%= @duration %></strong> minutes!</p>

app/views/charges/_new.html.erb
<script src="https://js.stripe.com/v3/"></script>
<div class="stripe-center">
  <div class="cell example example2">
    <div class="container-lg">
      <%= form_with model: current_user, id: "payment-form", method: "post", url: add_payment_path, local:true do %>
        <div id="card-errors"></div>
        <div data-locale-reversible="">
          <div class="row">
            <div class="field">
              <input id="example2-address" data-tid="elements_examples.form.address_placeholder" class="input empty" type="text" placeholder="185 Berry St" required="">
              <label for="example2-address" data-tid="elements_examples.form.address_label">Address</label>
              <div class="baseline"></div>
            </div>
          </div>
          <div class="row" data-locale-reversible="">
            <div class="field half-width">
              <input id="example2-city" data-tid="elements_examples.form.city_placeholder" class="input empty" type="text" placeholder="San Francisco" required="">
              <label for="example2-city" data-tid="elements_examples.form.city_label">City</label>
              <div class="baseline"></div>
            </div>
            <div class="field quarter-width">
              <input id="example2-state" data-tid="elements_examples.form.state_placeholder" class="input empty" type="text" placeholder="CA" required="">
              <label for="example2-state" data-tid="elements_examples.form.state_label">State</label>
              <div class="baseline"></div>
            </div>
            <div class="field quarter-width">
              <input id="example2-zip" data-tid="elements_examples.form.postal_code_placeholder" class="input empty" type="text" placeholder="94107" required="">
              <label for="example2-zip" data-tid="elements_examples.form.postal_code_label">ZIP</label>
              <div class="baseline"></div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="field">
            <br>
            <div id="card-element"><label for="example2-card-element" data-tid="elements_examples.form.card_label">Card Number</label></div>
            <div class="baseline"></div>
          </div>
        </div>
        <button type="submit" data-tid="elements_examples.form.pay_button">Save card details</button>
        <div class="error" role="alert"></div>
      <% end %>
    </div>
    <script>
      function getInfo(){
        // to test live on page,
        // console.log(getInfo());
      
        var address_1 = document.getElementById('example2-address').value;
        var city = document.getElementById('example2-city').value;
        var state = document.getElementById('example2-state');
        var postal_code = document.getElementById('example2-zip').value;
      
        var userInfo = {
          owner: {
            name: '<%= current_user.name %>',
            address: {
              line1: address_1,
              city: city,
              postal_code: postal_code,
                },
                email: '<%= current_user.email %>'
              },
          };
          return userInfo;
        }
      function stripeSourceHandler(source) {
          // Insert the source ID into the form so it gets submitted to the server
          var form = document.getElementById('payment-form');
          var hiddenInput = document.createElement('input');
          hiddenInput.setAttribute('type', 'hidden');
          hiddenInput.setAttribute('name', 'stripeSource');
          hiddenInput.setAttribute('value', source.id);
          form.appendChild(hiddenInput);
      
          // Submit the form
          form.submit();
      }
    </script>
    <script>
      var form = document.getElementById('payment-form');
      var stripe = Stripe("<%= ENV['STRIPE_PUBLIC_KEY'] %>"),
      
          elements = stripe.elements({
            fonts: [
              {
                cssSrc: 'https://fonts.googleapis.com/css?family=Source+Code+Pro',
              },
            ],
            locale: window.__exampleLocale
          }),
      
      
      
          elementStyles = {
            base: {
              color: '#32325D',
              fontWeight: 500,
              fontFamily: 'Source Code Pro, Consolas, Menlo, monospace',
              fontSize: '16px',
              fontSmoothing: 'antialiased',
      
              '::placeholder': {
                color: '#CFD7DF',
              },
              ':-webkit-autofill': {
                color: '#e39f48',
              },
            },
            invalid: {
              color: '#E25950',
      
              '::placeholder': {
                color: '#FFCCA5',
              },
            },
          },
      
          elementClasses = {
            focus: 'focused',
            empty: 'empty',
            invalid: 'invalid',
          };
      
          // Create an instance of the card Element.
        var card = elements.create('card', {style: elementStyles, class: elementClasses});
      
        // Add an instance of the card Element into the `card-element` <div>.
        card.mount('#card-element');
      
        // EVENT LISTENERS
      
        var  inputs = document.querySelectorAll('.cell.example.example2 .input');
          Array.prototype.forEach.call(inputs, function(input) {
            console.log('IN HERE!')
            input.addEventListener('focus', function() {
              input.classList.add('focused');
            });
            input.addEventListener('blur', function() {
              input.classList.remove('focused');
            });
            input.addEventListener('keyup', function() {
              if (input.value.length === 0) {
                input.classList.add('empty');
              } else {
                input.classList.remove('empty');
              }
            });
          });
      
      card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
          displayError.textContent = event.error.message;
        } else {
          displayError.textContent = '';
        }
      });
      
      
      form.addEventListener('submit', function(event) {
        event.preventDefault();
        var ownerInfo = getInfo();
      
        stripe.createSource(card, ownerInfo).then(function(result) {
          if (result.error) {
      // Inform the user if there was an error
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
          } else {
          // Send the source to your server
          stripeSourceHandler(result.source);
          }
        });
      });
    </script>
  </div>
</div>

app/views/charges/_show.html.erb
<!-- STRIPE - PAYMENT SUCCESS MESSAGE -->

<p>Call duration: <%= Utils.format_hhmmss(duration) %></p>
<p>You paid: <%= Utils.format_aud_cents(price) %></p>

app/views/charges/_show_earnings.html.erb
<!-- STRIPE - EARNINGS SUCCESS MESSAGE -->

<p>Call duration: <%= Utils.format_hhmmss(duration) %></p>
<p>You earned: <%= Utils.format_aud_cents(earnings) %></p>

app/views/charges/create_charge.html.erb
<p>hello world</p>